<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Name Application - Homepage</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>

		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    </head>
    <body>
		<div class="col-xs-12 col-sm-12">
			<?php if (isset($name)) : ?>
	            <h2>Welcome to my project, <?= htmlspecialchars($name); ?>!</h2>
			<?php else: ?>
				<p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>
			<?php endif; ?>
		</div>
		
    </body>
</html>
