<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Name Application - Homepage</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
		
    </head>
    <body>
	    <div class="container-fluid">
	    <div class="col-xs-12 col-sm-12 mt-4">
		    <div class="jumbotron jumbotron-fluid">
			<div class="container">
				<h1 class="display-3">Discover the meaning of your name</h1>
				<p class="lead">Using the form below will return data from the internet on your name.</p>
				</div>
			</div>
	    </div>
	    
		<div class="col-xs-12 col-sm-12">	
		<form>
		  <div class="form-group">
		    <label for="formFirstNameInput">First Name</label>
		    <input type="text" class="form-control" id="formFirstNameInput" placeholder="First name">
		  </div>
		  <div class="form-group">
		    <label for="formLastNameInput">Last Name</label>
		    <input type="text" class="form-control" id="formLastNameInput" placeholder="Last name">
		  </div>
		  
		  <button type="submit" class="btn btn-success">Submit</button>
		</form>
		</div>
	    </div>
    </body>
</html>
